#MySQL
primarydb:
  url: "jdbc:mysql://localhost:3306/maxrocky"
  driverClassName: "com.mysql.jdbc.Driver"
  username: "root"
  password: "connection1"
  initialSize: 5
  maxIdle: 10
  maxActive: 50
  validationQuery: "select 1"

