package com.rain.config.context;

/**
 * @author ron
 *         2016/5/19.
 */
public interface ContextConstants {
    String SYS_PLIT_CHAR = "";
    /**
     *  request Appcontext;
     * */
    String REQUEST_CONTEXT_NAME = SYS_PLIT_CHAR + "AOG_CONTEXT" + SYS_PLIT_CHAR;

    /**
     *  context key
     * */
    //inner param
    String KEY_USER = SYS_PLIT_CHAR + "USER" + SYS_PLIT_CHAR;
    String KEY_REQUEST = SYS_PLIT_CHAR + "REQUEST" + SYS_PLIT_CHAR;
    String KEY_MULTIPART_REQUEST = SYS_PLIT_CHAR + "MULTIPART_REQUEST" + SYS_PLIT_CHAR;
    String KEY_RESPONSE = SYS_PLIT_CHAR + "RESPONSE" + SYS_PLIT_CHAR;
    String KEY_REQUESTID = SYS_PLIT_CHAR + "REQUEST_ID" + SYS_PLIT_CHAR;

    //request params
    String KEY_UDID_PARAM = SYS_PLIT_CHAR + "UDID_PARAM" + SYS_PLIT_CHAR;
    String KEY_URI_PARAM = SYS_PLIT_CHAR + "URI_PARAM" + SYS_PLIT_CHAR;
    String KEY_AGENT_PARAM = SYS_PLIT_CHAR + "AGENT_PARAM" + SYS_PLIT_CHAR;
    String KEY_VERSION_PARAM = SYS_PLIT_CHAR + "VERSION_PARAM" + SYS_PLIT_CHAR;
    String KEY_DEVICE_PARAM = SYS_PLIT_CHAR + "DEVICE_PARAM" + SYS_PLIT_CHAR;
    String KEY_JSONP_CALLBACK_PARAM = SYS_PLIT_CHAR + "JSONP_CALLBACK_PARAM" + SYS_PLIT_CHAR;
    String KEY_OUTPUT_TYPE_PARAM = SYS_PLIT_CHAR + "OUTPUT_PARAM" + SYS_PLIT_CHAR;
    String KEY_REQUEST_PARAM_MAP = SYS_PLIT_CHAR + "REQUEST_PARAM_MAP" + SYS_PLIT_CHAR;
    String KEY_REQUEST_PARAM_MD5_KEY = SYS_PLIT_CHAR + "REQUEST_PARAM_MAP_MD5" + SYS_PLIT_CHAR;
    String KEY_REQUEST_PARAM_IP = SYS_PLIT_CHAR + "REQUEST_PARAM_IP" + SYS_PLIT_CHAR;

    //sessionkey
    String KEY_SESSIONKEY_PARAM = SYS_PLIT_CHAR + "SESSIONKEY_PARAM" + SYS_PLIT_CHAR;
}
